# Generated by Django 2.2.7 on 2019-12-01 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_subject_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bangla', models.CharField(max_length=30)),
                ('mathmathics', models.CharField(max_length=30)),
                ('english', models.CharField(max_length=30)),
                ('studentformsave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Std_subject_list', to='projectapp.student_form')),
            ],
        ),
    ]
