# Generated by Django 2.2.7 on 2019-12-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_student_four_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_four_subject',
            name='fourth_subject',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Higher Math', 'Higher Math'), ('Agriculture', 'Agriculture')], max_length=30),
        ),
    ]
